export const CHANGE_TOP_BANNERS="CHANGE_TOP_BANNERS"
export const GET_HOT_RECOMMENDS="GET_HOT_RECOMMENDS"
export const CHANGE_NEW_ALBUMT="CHANGE_NEW_ALBUMT"
export const CHANGE_TOP_LIST="CHANGE_TOP_LIST"